# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  # Hold ourselves to a high bar
  range: 85..100
  round: down
  precision: 1
  status:
    project: off
    patch: off

# Test files aren't important for coverage
ignore:
  - "tests"
  - "hls"
  - "book-lints"

# Make comments less noisy
comment:
  layout: "files"
  require_changes: yes
