[package]
name = "hemtt-sign"
version = "0.4.0"
authors = ["Brett <brett@mayson.io>"]
edition = "2018"

[dependencies]
hemtt-pbo = { path = "../hemtt-pbo" }
hemtt-io = { path = "../hemtt-io" }
colored = "2.0"
lazy_static = "1.4"
clap = "2.33"
openssl = "0.10"
byteorder = "1.3"
