[package]
name = "hemtt-pbo"
version.workspace = true
edition.workspace = true
description = "An PBO library for hemtt"
license = "GPL-2.0"

[lints]
workspace = true

[lib]
bench = false

[dependencies]
hemtt-common = { path = "../common" }
hemtt-lzo = { path = "../lzo" }

byteorder = { workspace = true }
indexmap = { workspace = true }
sha-1 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
fs-err = { workspace = true }
hemtt-workspace = { path = "../workspace" }
insta = { workspace = true }

[[bench]]
name = "small_files"
harness = false

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-Wl,--no-rosegment"]
