[package]
name = "hemtt-lzo"
version.workspace = true
edition.workspace = true
description = "An LZO library for hemtt"
license = "GPL-2.0"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }

[[bench]]
name = "compress"
harness = false
required-features = ["compress", "decompress"]

[features]
default = ["compress", "decompress"]
compress = []
decompress = []
