[package]
name = "hemtt-lzo"
version.workspace = true
edition.workspace = true
description = "An LZO library for hemtt"
license = "GPL-2.0"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[features]
default = ["compress", "decompress"]
compress = []
decompress = []
