name: Language Server

on:
  push:
    branches: [main]
    tags:
      - v*
      - hls-v*
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner: ubuntu-22.04
            name: ubuntu
            artifact: linux-x64
            exe: hemtt-language-server
          - runner: windows-latest
            name: windows
            artifact: windows-x64
            exe: hemtt-language-server.exe
          - runner: macos-latest
            name: macos-arm
            artifact: macos-arm64
            exe: hemtt-language-server
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: hls-${{ matrix.os.name }}
      - name: Compile
        run: |
          cd hls
          cargo build --release --bin hemtt-language-server
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os.artifact }}
          path: target/release/${{ matrix.os.exe }}
      - name: Upload Language (Linux)
        if: startsWith(matrix.os.runner, 'ubuntu')
        uses: actions/upload-artifact@v7
        with:
          name: languages
          path: hls/languages

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: actions/download-artifact@v8
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: linux-x64
          path: linux
      - uses: actions/download-artifact@v8
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: windows-x64
          path: windows
      - name: Set Executable
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          chmod +x linux/hemtt-language-server
      - name: Move Server
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          mv linux/hemtt-language-server hls/hemtt-language-server
          mv windows/hemtt-language-server.exe hls/hemtt-language-server.exe
      - name: Remove Existing Languages
        run: |
          rm -rf hls/languages
      - name: Download Languages
        uses: actions/download-artifact@v8
        with:
          name: languages
          path: hls/languages
      - name: Package
        run: |
          cd hls
          npm install
          npm install -g @vscode/vsce
          vsce package
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: hls
          path: hls/*.vsix
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd hls
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Download Linux x64
        uses: actions/download-artifact@v8
        with:
          name: linux-x64
      - name: Rename Linux x64
        run: |
          mv hemtt-language-server hls-linux-x64
      - name: Download Windows x64
        uses: actions/download-artifact@v8
        with:
          name: windows-x64
      - name: Rename Windows x64
        run: |
          mv hemtt-language-server.exe hls-windows-x64
      - name: Download MacOS ARM64
        uses: actions/download-artifact@v8
        with:
          name: macos-arm64
      - name: Rename MacOS ARM64
        run: |
          mv hemtt-language-server hls-macos-arm64
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            hls-linux-x64
            hls-windows-x64
            hls-macos-arm64
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
