name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os.runner }}
    name: ${{ matrix.os.name }} / ${{ matrix.toolchain }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner: ubuntu-latest
            name: ubuntu
          - runner: windows-latest
            name: windows
          - runner: macos-latest
            name: macos
        toolchain:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Arma 3 Tools
        if: startsWith(matrix.os.runner, 'windows')
        uses: arma-actions/arma3-tools@master
        with:
          toolsUrl: ${{ secrets.ARMA3_TOOLS_URL }}
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: taiki-e/install-action@nextest
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      # https://twitter.com/jonhoo/status/1571290371124260865
      - name: cargo test --locked
        run: cargo nextest run --locked --all-features --all-targets
