[package]
name = "hemtt-core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["serde"]
test = []

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
serde =  { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
serde_json = { workspace = true }
